### ISSUE TITLE
Error when trying to connect to SP Online

### ISSUE THREAD

**Issue by DovydasADL** [bandrben/SPTaxonomyToolsOnline#6]
Hey, I'm getting this error when trying to connect to my SP Online site:

ERROR: System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)

**Comment by geofft68** [comment]
I'm getting the exact same error when trying to connect to SPOnline and used the tool successfully about 2 weeks ago so this looks like a recent issue.

**Comment by DovydasADL** [comment]
I have found the fix. The error is because of this code using older NET Framework and TLS protocols.
At the moment Sharepoint Online allows only newer TLS 1.2 protocol.
To fix this issue add these lines to SPTaxonomyToolsOnline.exe.config file: 
` <runtime>
	<AppContextSwitchOverrides value="Switch.System.Net.DontEnableSchUseStrongCrypto=false" />
</runtime>`
